import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { GlobalContextProvider } from './providers/GlobalContextProvider';
import { ThemeProvider } from './providers/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <GlobalContextProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='dark'
            enableSystem
            disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
